####################################
# Kubernetes related configuration #
####################################

# jizt namespace. All jizt resources
# will be deployed in this namespace
namespace: "default"

# Ingress configuration
# ref: http://kubernetes.io/docs/user-guide/ingress/
ingress:
  hostname: "api.jizt.it"
  paths:
    v1: "/v1/summaries/*"

# General replica count for ALL the deployments
replicaCount: 1

# Autoscaling configuration
# ref: https://kubernetes.io/blog/2016/07/autoscaling-in-kubernetes/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80


#######################################
# Microservices related configuration #
#######################################

# Configuration for the Dispatcher microservice
dispatcher:
  name: "dispatcher"
  ports:
    svc: 5000
    container: 5000
  image: eu.gcr.io/jizt-299516/dispatcher:0.0.70

# Configuration for ConfigMap/Secret containing
# PostgreSQL connection details
postgres:
  host: "db-cluster.jizt-db"  # clusterName.namespace
  dbName: "jizt"
  secret:
    secretName: pg-dispatcher
    volumeName: postgres-user
    mountPath: "/etc/postgres"
    usernameFile: "username"
    passwordFile: "password"

# Configuration for the Text Preprocessor microservice
textPreprocessor:
  name: "text-preprocessing"
  ports:
    svc: 5000
    container: 5000
  image: eu.gcr.io/jizt-299516/text-preprocessor:0.0.11

# Configuration for the Text Encoder microservice
t5LargeTextEncoder:
  name: "t5-large-text-encoding"
  ports:
    svc: 5000
    container: 5000
  image: eu.gcr.io/jizt-299516/t5-large-text-encoder:0.0.20
  volumeMounts:
    modelsMountPath: "/home/text_encoder/models"
    tokenizerPath: "t5-small/tokenizer"  # TODO: change to t5-large

# Configuration for the Text Summarizer microservice
t5LargeTextSummarizer:
  name: "t5-large-text-summarization"
  ports:
    svc: 5000
    container: 5000
  image: eu.gcr.io/jizt-299516/t5-large-text-summarizer:0.0.24
  volumeMounts:
    modelsMountPath: "/home/text_summarizer/models"
    tokenizerPath: "t5-small/tokenizer"  # TODO: change to t5-large
    modelPath: "t5-small/model"  # TODO: change to t5-large
  params:
    configMapName: t5-large-params
    # The max length of the summary will be at most
    # this percentage of the source length
    relative_max_length: 0.4  # float
    # Same for the min length
    relative_min_length: 0.1  # float
    do_sample: True  # bool
    early_stopping: None  # bool
    num_beams: 4  # int
    temperature: None  # float
    top_k: None  # int
    top_p: None  # float
    repetition_penalty: None  # float
    length_penalty: None  # float
    no_repeat_ngram_size: 4  # int

# Configuration for the Text Postprocessor microservice
textPostprocessor:
  name: "text-postprocessing"
  ports:
    svc: 5000
    container: 5000
  image: eu.gcr.io/jizt-299516/text-postprocessor:0.0.17


#################################
# Volumes related configuration #
#################################

# Configuration for the models StorageClass
modelsStorageClass:
  name: models
  volumeBindingMode: WaitForFirstConsumer
  allowVolumeExpansion: true

# Configuration for the models PersistentVolume
modelsPV:
  name: models
  capacity:
    storage: 10Gi
  pvReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: models
    fsType: ext4
  csi:
    driver: pd.csi.storage.gke.io
    volumeHandle: models  # volume name
    readOnly: true
    fsType: ext4


###############################
# Kafka related configuration #
###############################

# Configuration for Strimzi Kafka cluster
# ref: https://strimzi.io/docs/operators/master/using.html#proc-config-kafka-str
kafka:
  name: "jizt-cluster"
  namespace: "default"  # not to be confused with strimzi-operator namespace
  version: 2.6.0
  replicas: 1
  resources:
    memoryRequests: 1Gi
    memoryLimits: 1Gi
  config:
    autoCreateTopics: "false"
    messageMaxBytes: 1048588  # 1 MiB
    topicReplicationFactor: 1
    logReplicationFactor: 1
    logMinIsr: 1
    logMessageFormatVersion: "2.6-IV0"
  zookeeper:
    replicas: 1

# Global configuration for Kafka topics
# ref: https://strimzi.io/docs/operators/master/using.html#type-KafkaTopic-reference
topics:
  partitions: 1
  replicas: 1
  retentionMs: 600000  # 10 minutes
