name: Deploy to GKE

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: jizt-med-cluster-3
  GKE_ZONE: europe-west2-a
  RELEASE_NAME: jizt
  HELM_PATH: src/helm/jizt

jobs:
  test-deploy:
    name: Test & Deploy JIZT
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name:

    - name: Run tests
      run: pytest tests --ignore tests/test_text_encoding.py
      
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT_ID }}
        
    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.2.1
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    - name: Upgrade JIZT
      run: |-
        helm upgrade ${{ env.RELEASE_NAME }} ${{ env.HELM_PATH }}
